### ISSUE TITLE
Rider ebuild

### ISSUE THREAD

**Issue by alem0lars** [rindeal/rindeal-ebuild-repo#208]
JetBrains released Rider (C# IDE).

I'd like to know if it's possible to have the ebuild of that software.

Thanks

**Comment by rindeal** [comment]
I've pushed the new package to _master_, so please give it a try and report back if it'll work for you as it is.

**Comment by alem0lars** [comment]
I've performed the sync but I still don't see the ebuild available.

**Comment by rindeal** [comment]
So, the ebuild is not on your machine at all or it's just not showing up for emerge?

**Comment by alem0lars** [comment]
Ok, I've re-cloned the repo and now it works.

Thanks.

**Comment by alem0lars** [comment]
I've installed rider. However when I try to start it I get a Java error (with stacktrace).

Do you also get that error or it's just me?

**Comment by rindeal** [comment]
Try now.
