### ISSUE TITLE
libpsl fails to build on base image

### ISSUE THREAD

**Issue by rindeal** [rindeal/rindeal-ebuild-repo#243]
https://travis-ci.com/rindeal/ebuild-pkg-emerge-tester/builds/78027522

**Comment by prototype99** [comment]
is it fixed now? 0.20.2 built fine for me

**Comment by rindeal** [comment]
It's not fixed yet, but you can merge it safely, because you have all the undeclared deps installed for sure. Thid issue is concern only of the stripped down base docker image.

**Comment by rindeal** [comment]
caused by a missing gtk-doc dep
